// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using soulBalanceGs.Data;

#nullable disable

namespace soulBalanceGs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123152353_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("soulBalanceGs.Models.Atividade", b =>
                {
                    b.Property<int>("AtividadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AtividadeId"));

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("DuracaoMinutosAtividade")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("TipoAtividade")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("AtividadeId");

                    b.HasIndex("FkIdUsuario");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("soulBalanceGs.Models.CheckinManual", b =>
                {
                    b.Property<int>("ChekinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("chekin_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChekinId"));

                    b.Property<string>("Energia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("energia");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("fk_id_usuario");

                    b.Property<string>("Foco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("foco");

                    b.Property<string>("Humor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("humor");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("time");

                    b.HasKey("ChekinId");

                    b.HasIndex("FkIdUsuario");

                    b.ToTable("CheckinManuais");
                });

            modelBuilder.Entity("soulBalanceGs.Models.DadosSensor", b =>
                {
                    b.Property<int>("DadosSensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DadosSensorId"));

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("TipoDado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Valor")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("DadosSensorId");

                    b.HasIndex("FkIdUsuario");

                    b.ToTable("DadosSensores");
                });

            modelBuilder.Entity("soulBalanceGs.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TB_SOUL_BALANCE_USUARIO");
                });

            modelBuilder.Entity("soulBalanceGs.Models.Atividade", b =>
                {
                    b.HasOne("soulBalanceGs.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("soulBalanceGs.Models.CheckinManual", b =>
                {
                    b.HasOne("soulBalanceGs.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("soulBalanceGs.Models.DadosSensor", b =>
                {
                    b.HasOne("soulBalanceGs.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
